#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 0594e227-62c6-4f81-ab37-19573e77b1cb
# Source File: HappyHalloween.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
2A0AAB+LCAAAAAAABAC9V99v2jAQfp+0/yHKw54QEH6MVoNIDV3Vqu2KSNftrTLOAV4dO7JNIfvr
dyGhA1JIWhWESEji7+6+u+/OoTsEKp9BxefEEAt/aCZFz25UHdv9/MmyuneKTZgg/IJx+EFCcC9J
FMWXhHM5BxDVSI+7tdyiFDr6A9RYJo6gZ/uxNhBWfzERyLmuXkgVpseK9dqjivWQxdKq1pNPxerP
uJkp6AmYGUV4xRrMRpzRa4jv5ROI3qjTIW3a/uqcNltQPzm1LYGh9Owx2tsM2rbolPFAIcjuS2GU
5Dqli1EPlIxAmThDn1EKkfFmxkixWoOrhjAGxFPIlo2WC+6ubau2MlRbWdpleWakTwmHcxaCSLhi
EF8rltMsD72VAdjuBXIoxHiEPvUllwqdtCpW+i1E9TkDYXz2F920mk7FanXqhaCkgp5UASjfxDwJ
kC0gOGeEy0kh+JYsWIj+PLlAIOEaiiFMvBWSqNR289IoBPqGKDOQmhmWCKKP2UGaVJXB3sPC2GkD
WXs8fn9GoxnkRpLgtTgfkwfd2nLpClfcbwNGkxbCPB2866LU1UgunH3tlk/SjaQkza3TwGZo5PKz
q5hrHktgMknXT1HSTqcE4J6MrkQAqLAy5nG1b2S0S45bVcYuo08bDB6Xt7YKXEsrXL7e6dg6eK3/
D7+3FPpM0GkyjTyJaNwGhmwyzY+xvYPM4yRJUiEkHT1D0EjQdu+uS0AwR5B58YkIYk/Jeb5X98m3
2cJh3mq2Swt4lcbS6u20K1Yjv1vs025+eO8aU19IGH0rFcxPDQ9MzwhfTvu18uwYxesy3rwoVvRV
SCZww7Q5uKhZ4omjJ2fXq8GS5Tm+HUxtd3k68VjxPrxkkNav0UaF4KF441BE6IhgY5kstWt3ttCb
GT3TGkLkC3plOrsTu6GmUnE2+oCcdWsvVre9pFU6ho8PV0Kxx+Sl+TiOFJkzMXmPr3pz3B53xo4T
tOukSYp9/Q75cTgxhTKVKvZBPTMK7yrZm9n1ca4fhV7GCnsTqR2A28tl2tvd2vo/OfcfPB2tINgN
AAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2016 v5.2.129
     Generated on:       10/31/2016 9:43 AM
     Generated by:       June Blender
     Organization:       SAPIEN Technologies, Inc
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2016
#>
#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-HappyHalloween_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formHappyHalloween = New-Object 'System.Windows.Forms.Form'
	$picturebox1 = New-Object 'System.Windows.Forms.PictureBox'
	$buttonOK = New-Object 'System.Windows.Forms.Button'
	$imagelist1 = New-Object 'System.Windows.Forms.ImageList'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	$imageLogo = [System.Drawing.Image]::FromFile('C:\Users\JuneBlender\OneDrive\SAPIEN-juneb-sapien\Art\Halloween_SAPIEN-BUTTON-LOGO-2 - Small.png')
	$imageCrew = [System.Drawing.Image]::FromFile('C:\Users\JuneBlender\OneDrive\SAPIEN-juneb-sapien\Art\Halloween2015.png')
	
	$formHappyHalloween_Load={	
		$picturebox1.Image = $imageLogo
	}
	
	$picturebox1_Click = {
		
		if ($picturebox1.Image -eq $imageLogo)
		{
			$picturebox1.Image = $imageCrew
			$formHappyHalloween.Text = "Happy Halloween from the SAPIEN Crew"
		}
		else
		{
			$picturebox1.Image = $imageLogo
			$formHappyHalloween.Text = "Happy Halloween"
		}
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formHappyHalloween.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$picturebox1.remove_Click($picturebox1_Click)
			$formHappyHalloween.remove_Load($formHappyHalloween_Load)
			$formHappyHalloween.remove_Load($Form_StateCorrection_Load)
			$formHappyHalloween.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formHappyHalloween.SuspendLayout()
	#
	# formHappyHalloween
	#
	$formHappyHalloween.Controls.Add($picturebox1)
	$formHappyHalloween.Controls.Add($buttonOK)
	$formHappyHalloween.AcceptButton = $buttonOK
	$formHappyHalloween.AutoScaleDimensions = '6, 13'
	$formHappyHalloween.AutoScaleMode = 'Font'
	$formHappyHalloween.BackColor = '64, 64, 64'
	$formHappyHalloween.ClientSize = '431, 470'
	$formHappyHalloween.FormBorderStyle = 'FixedDialog'
	$formHappyHalloween.MaximizeBox = $False
	$formHappyHalloween.MinimizeBox = $False
	$formHappyHalloween.Name = 'formHappyHalloween'
	$formHappyHalloween.StartPosition = 'CenterScreen'
	$formHappyHalloween.Text = 'Happy Halloween'
	$formHappyHalloween.add_Load($formHappyHalloween_Load)
	#
	# picturebox1
	#
	$picturebox1.Location = '12, 12'
	$picturebox1.Name = 'picturebox1'
	$picturebox1.Size = '409, 417'
	$picturebox1.TabIndex = 1
	$picturebox1.TabStop = $False
	$picturebox1.add_Click($picturebox1_Click)
	#
	# buttonOK
	#
	$buttonOK.Anchor = 'Bottom, Right'
	$buttonOK.BackColor = 'Black'
	$buttonOK.DialogResult = 'OK'
	$buttonOK.ForeColor = 'SandyBrown'
	$buttonOK.Location = '346, 435'
	$buttonOK.Name = 'buttonOK'
	$buttonOK.Size = '75, 23'
	$buttonOK.TabIndex = 0
	$buttonOK.Text = '&OK'
	$buttonOK.UseVisualStyleBackColor = $False
	#
	# imagelist1
	#
	$imagelist1.ColorDepth = 'Depth8Bit'
	$imagelist1.ImageSize = '256, 256'
	$imagelist1.TransparentColor = 'Transparent'
	$formHappyHalloween.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formHappyHalloween.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formHappyHalloween.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formHappyHalloween.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formHappyHalloween.ShowDialog()

} #End Function

#Call the form
Call-HappyHalloween_psf | Out-Null
